### ISSUE TITLE
'Episode' object has no attribute '_autoReload'

### ISSUE THREAD

**Issue by meisnate12** [pkkid/python-plexapi#952] opened 2022-05-30 07:09 UTC
### Describe the Bug

I've had a few Plex Meta Manager Users report getting an `'Episode' object has no attribute '_autoReload'` Error and all I'm doing is calling `.episodes` on a Season object [PMM Issue 895](https://github.com/meisnate12/Plex-Meta-Manager/issues/895) any idea whats going on?

### Code Snippets

```python
# Example 1


Traceback (most recent call last):                                                                                                                                                      |
  File "//plex_meta_manager.py", line 494, in run_libraries
    library_status[library.name]["Library Overlays"] = library.Overlays.run_overlays()
  File "/modules/overlays.py", line 47, in run_overlays
    key_to_overlays, properties = self.compile_overlays()
  File "/modules/overlays.py", line 256, in compile_overlays
    builder.filter_and_save_items(builder.gather_ids(method, value))
  File "/modules/builder.py", line 1663, in filter_and_save_items
    if self.check_filters(item, f"{(' ' * (max_length - len(str(i))))}{i}/{total}"):
  File "/modules/builder.py", line 2163, in check_filters
    if self.library.check_filters(item, self.filters, self.current_time) is False:
  File "/modules/plex.py", line 1188, in check_filters
    if self.check_filter(item, filter_attr, modifier, filter_final, filter_data, current_time) is False:
  File "/modules/plex.py", line 1272, in check_filter
    sub_items = item.episodes()
  File "/usr/local/lib/python3.9/site-packages/plexapi/video.py", line 560, in episodes
    return self.fetchItems(key, Episode, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/plexapi/base.py", line 268, in fetchItems
    items = self.findItems(data, cls, ekey, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/plexapi/base.py", line 293, in findItems
    item = self._buildItemOrNone(elem, cls, initpath)
  File "/usr/local/lib/python3.9/site-packages/plexapi/base.py", line 104, in _buildItemOrNone
    return self._buildItem(elem, cls, initpath)
  File "/usr/local/lib/python3.9/site-packages/plexapi/base.py", line 89, in _buildItem
    return cls(self._server, elem, initpath, parent=self)
  File "/usr/local/lib/python3.9/site-packages/plexapi/base.py", line 54, in __init__
    self._loadData(data)
  File "/usr/local/lib/python3.9/site-packages/plexapi/video.py", line 830, in _loadData
    if self.skipParent and not self.parentRatingKey:
  File "/usr/local/lib/python3.9/site-packages/plexapi/base.py", line 476, in __getattribute__
    if self._autoReload is False: return value
  File "/usr/local/lib/python3.9/site-packages/plexapi/base.py", line 468, in __getattribute__
    value = super(PlexPartialObject, self).__getattribute__(attr)
AttributeError: 'Episode' object has no attribute '_autoReload'

'Episode' object has no attribute '_autoReload'



# Example 2



Traceback (most recent call last):
  File "//plex_meta_manager.py", line 491, in run_libraries
    library_status[library.name]["Library Operations"] = library.Operations.run_operations()
  File "/modules/operations.py", line 85, in run_operations
    self.library.find_and_upload_assets(item)
  File "/modules/plex.py", line 947, in find_and_upload_assets
    for episode in self.query(season.episodes):
  File "/usr/local/lib/python3.9/site-packages/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python3.9/site-packages/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python3.9/site-packages/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python3.9/site-packages/six.py", line 719, in reraise
    raise value
  File "/usr/local/lib/python3.9/site-packages/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/modules/plex.py", line 507, in query
    return method()
  File "/usr/local/lib/python3.9/site-packages/plexapi/video.py", line 669, in episodes
    return self.fetchItems(key, Episode, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/plexapi/base.py", line 268, in fetchItems
    items = self.findItems(data, cls, ekey, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/plexapi/base.py", line 293, in findItems
    item = self._buildItemOrNone(elem, cls, initpath)
  File "/usr/local/lib/python3.9/site-packages/plexapi/base.py", line 104, in _buildItemOrNone
    return self._buildItem(elem, cls, initpath)
  File "/usr/local/lib/python3.9/site-packages/plexapi/base.py", line 89, in _buildItem
    return cls(self._server, elem, initpath, parent=self)
  File "/usr/local/lib/python3.9/site-packages/plexapi/base.py", line 54, in __init__
    self._loadData(data)
  File "/usr/local/lib/python3.9/site-packages/plexapi/video.py", line 830, in _loadData
    if self.skipParent and not self.parentRatingKey:
  File "/usr/local/lib/python3.9/site-packages/plexapi/base.py", line 476, in __getattribute__
    if self._autoReload is False: return value
  File "/usr/local/lib/python3.9/site-packages/plexapi/base.py", line 468, in __getattribute__
    value = super(PlexPartialObject, self).__getattribute__(attr)
AttributeError: 'Episode' object has no attribute '_autoReload'
'Episode' object has no attribute '_autoReload'
```

### Expected Behavior

im expecting all the episodes to return 

### Operating System and Version

I can ask the users if needed

### Plex Media Server Version

I can ask the users if needed

### Python Version

At least 3.7

### PlexAPI Version

4.11.1

**Comment by KnifeFed** [comment] 2022-05-30 12:28
This happens if you have `Seasons` set to `Hide` in the library advanced settings or for a specific show.

**Comment by JonnyWong16** [comment] 2022-05-30 15:43
Duplicate of #945.

**Closed by JonnyWong16** 2022-05-30 15:43 UTC
