### ISSUE TITLE
Adding IMDb/TMDb search filter for the new plex movie agent

### ISSUE THREAD

**Issue by Mnk3y** [pkkid/python-plexapi#557] opened 2020-08-21 11:14 UTC
Since the last update of the new agent there is no IMDb/TMDb id in the guid attribute of the video element anymore. Instead, 2 new entries have been added to the XML.

For example `<Guid id="imdb://tt0054215"/>` and `<Guid id="tmdb://539"/>`.

The guid attribute looks like this now `guid="plex://movie/5d7768264de0ee001fcc87e0"`.
With the old agent it looked like this `guid="com.plexapp.agents.imdb://tt0054215"`.

So now you can no longer search for the IMDb id like this `search(guid='imdb://tt0054215')`.

**Comment by PearsonFlyer** [comment] 2020-09-06 17:11
Just a note that this is no longer in beta. Thank you for all you do!

**Comment by blacktwin** [comment] 2020-10-12 17:52
`search(guid='12345')` only worked because `guid` was hardcoded into the `ALLOWED_FILTERS` for the different library types. The search would pull the entire library and search for the `guid` instead of using Plex to apply it's filtering. `ALLOWED_FILTERS` has been [removed](https://github.com/pkkid/python-plexapi/commit/ea6538f596b38fc6b96fec1758d9227cd5bcb91e) in favor of using the libraries known filters. Because searching via guid is not supported in the webUI it is now, not supported in this project. That is IMO the scope of this project. Obviously, that can be changed with an approved PR.  

Check out this [comment](https://github.com/adamgot/python-plexlibrary/issues/90#issuecomment-707221088) in the above mentioned thread for good overview for what can happen next.

**Comment by josh-gaby** [comment] 2020-10-13 00:36
@blacktwin searching by guid may not be supported in the webUI but you can still filter by it when access the plex URLs directly, does this mean that it will still work since it's a valid filter or have I got the wrong idea about what a filter is?

i.e. 
`PLEX_URL/library/all?guid=plex://movie/5d9f3dc2ca3253001ef32b76&X-Plex-Token=XXXX` returns the Police Academy movie
and 
`PLEX_URL/library/all?guid=thetvdb://71663&X-Plex-Token=XXXX` returns The Simpsons TV series

**Comment by blacktwin** [comment] 2020-10-13 02:11
@josh-gaby Searching by `guid` still works. But it looks like it's dependent on which search you're using.

```
plex.library.search(guid='com.plexapp.agents.imdb://tt8695030')                    # works
plex.library.section('Movies').search(guid='com.plexapp.agents.imdb://tt8695030')  # does not work
plex..search(guid='com.plexapp.agents.imdb://tt8695030')                           # does not work
```
Back the issue, you cannot search for `tt8695030` like in the above example if that library is using the new Plex Movie Agent and that item has been updated.

**Comment by josh-gaby** [comment] 2020-10-13 02:50
@blacktwin so with this change will the `plex.library.search(guid='com.plexapp.agents.imdb://tt8695030')` guid search still work or will all of the guid searching be removed so that all search endpoints behave consistently?

**Comment by blacktwin** [comment] 2020-10-13 14:29
guid search as seen above works because that search uses the url structure you laid out `PLEX_URL/library/all?guid=...`. Thats not changing. Only the primary guid can be searched like that.

From the initial issue:
> So now you can no longer search for the IMDb id like this search(guid='imdb://tt0054215').

If the library uses the new Plex Movie Agent **and** the item in question has been updated **and** it's guid now starts with `plex://movie/...` **and** searching via guid with anything other than `plex://movie/...` will result in nothing.

The issue is that when the new Plex Movie Agent is used, it's guid (`plex://movie/...` ) is now the primary guid. The third party guids (tvdb, tmdb, imdb, etc.) are available in an items XML but there is no way to search for it if it is not the primary guid.

Here is an example of how you could search for `imdb://tt8695030` when every item in your Movies library has been updated to use the New Plex Movie Agent and PR #562 merged:
```python
for item in plex.library.section('Movies').all():
   for guid in item.guids:
        if guid.id == `imdb://tt8695030`:
            print('Found tt8695030 as {}. Plex Movie Agent GUID: {}'.format(item.title, item.guid))
```

> Check out this [comment](https://github.com/adamgot/python-plexlibrary/issues/90#issuecomment-707221088) in the above mentioned thread for good overview for what can happen next. 

The comment mentions creating a reverse dictionary lookup once then referencing that instead of running through the entire library each time. So those are our options, run through the entire library each run or the user/operation/third party app would create a reserve dictionary lookup once and reference that. Either way I don't think that this issue will be resolve within the project.

**Closed** 2021-10-04 20:56 UTC

**Comment by adrianherr** [comment] 2022-12-17 03:27
Hi. Is there a way to get a list of all the movies and their IMDB number?

**Comment by JonnyWong16** [comment] 2023-11-28 17:01
https://python-plexapi.readthedocs.io/en/latest/modules/library.html#plexapi.library.LibrarySection.getGuid
