### ISSUE TITLE
Make PlexServer.clients() more user friendly.

### ISSUE THREAD

**Issue by postlund** [pkkid/python-plexapi#126] opened 2017-02-22 18:52 UTC
I'm posting this on behalf of a fellow Home Assistant user 😄 He seems to get an error when the Plex integration tries to fetch active clients. The "port" attribute is missing in the XML-response from Plex:

```
17-02-18 06:29:08 ERROR (MainThread) [homeassistant.core] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.5/dist-packages/homeassistant/components/media_player/plex.py", line 117, in 
track_utc_time_change(hass, lambda now: update_devices(), second=30)
File "/usr/local/lib/python3.5/dist-packages/homeassistant/util/init.py", line 296, in wrapper
result = method(*args, **kwargs)
File "/usr/local/lib/python3.5/dist-packages/homeassistant/util/init.py", line 296, in wrapper
result = method(*args, **kwargs)
File "/usr/local/lib/python3.5/dist-packages/homeassistant/components/media_player/plex.py", line 123, in update_devices
devices = plexserver.clients()
File "/home/openflixr/.homeassistant/deps/plexapi/server.py", line 65, in clients
baseurl = 'http://%s:%s' % (elem.attrib['address'], elem.attrib['port'])
KeyError: 'port'
```
Has anyone seen this before? Any ideas on how to troubleshoot this? Original issue is here: https://github.com/home-assistant/home-assistant/issues/6019.

**Comment by Hellowlol** [comment] 2017-02-22 19:02
Nothing we can do about this. Imo we should parse the devices xml match the clientIdentifier or machineid then return the port.

**Comment by pkkid** [comment] 2017-02-22 21:20
This looks like a duplicate of Bug #74 Getting error on clients bug.

@Hellowlol Thats not a bad idea. We'll leave this open to make `PlexServer.clients()` a bit more user friendly.

**Comment by postlund** [comment] 2017-02-23 06:41
That would be great! I Do you know what could be the root cause of this (so we can work around it for know)?

**Comment by pkkid** [comment] 2017-02-23 06:56
I actually don't know, needs some more investigation.

**Comment by Hellowlol** [comment] 2017-02-23 07:14
I have plexpass and using the secord  lastest public version and it does not report my iphone port.

**Comment by pkkid** [comment] 2017-02-23 07:21
Well, those ideas have been debunked. :-P

**Comment by Hellowlol** [comment] 2017-02-23 08:33
@postlund Its abit messy but you could do:
````
from plexapi.myplex import MyPlexAccount
acc = MyPlexAccount('<username>', '<password>')

for device in acc.devices():
    if device.clientIdentifier == 'the other id':
         port = device._data.attrib.get('port')
````

**Comment by shenning00** [comment] 2017-02-23 17:41
I think this bug is also similar to this [114](https://github.com/pkkid/python-plexapi/issues/114).

Plex is very confusing about when certain data is represented or not.

**Comment by Hellowlol** [comment] 2017-02-26 22:52
https://github.com/pkkid/python-plexapi/pull/135/commits/53fab6239a222164f5aadf406262a06d70de4212 tries to get a port if its missing.

**Comment by pkkid** [comment] 2017-02-27 02:17
Add download log/db and stop playback #135
baeedce - add download log/db.			
53fab62 - fix tests for download logs/dbs  …			
cbde478 - Add stop playback.			
351fe35 - add websocket to requirements.txt  …			
a4abc0e - fixup

**Comment by pkkid** [comment] 2017-02-27 05:10
Reviewing it here.
https://github.com/pkkid/python-plexapi/pull/135/commits/53fab6239a222164f5aadf406262a06d70de4212

**Comment by postlund** [comment] 2017-02-27 08:31
Sorry about my delay... seems great though! I've heard from at least one more user with the same issue, so a solution to this will be appreciated!

**Comment by pkkid** [comment] 2017-05-19 03:18
Reviewed the changes from Hellowlol.  I found a few things that looked like bugs to me.  Feel free to comment if I am miss reading it. Also, I can see a case when the PlexServer token will not work to connect to plex.tv (if your browsing someone else server), I didn't do anything to resolve this.

* It was calling https://plex.tv/devices.xml, but treating it like a MyPlexResource object which are actually from https://plex.tv/api/resources. Those URLs advertise connections differently so I suspect it wasn't working correctly. Perhaps the URL was switched out last minute or something.
* Moved this logic to its own helper function and wrapped it in a try..except in case something fails.

commit a79bc44b7a43c1419e6b22913726d6dca8b4417f
Author: Michael Shepanski <mjs7231@gmail.com>
Date:   Thu May 18 23:04:57 2017 -0400
Ability to get a MyPlexAccount object from the plexServer object A(using same token).
Review code to lookup port if not available on the client listing (fixed a few bugs in it).

**Closed by pkkid** 2017-05-19 03:18 UTC
Labels: 3.0.0, enhancement, review
