### ISSUE TITLE
Cannot control client : 406 error

### ISSUE THREAD

**Issue by niko34** [pkkid/python-plexapi#244] opened 2018-01-03 10:48 UTC
Hi,

i try to control a plex client (PMP on a RPI) using python-plexapi.

I get a token after using plex-listtokens.py. The tool list many object : Ressources, Devices and one client (my PMP RPI). My Plex Media Server (Ressource) has the same token than my Plex Media Player (Client).

I made a small python script, where the baseurl is the url of my plex server.
When i print the clients list, i can see my client with the title "PlexMediaPlayer". 
As a result of this script, i always get a 406 error code, with this trace :
```
PlexMediaPlayer
Traceback (most recent call last):
  File "./test.py", line 16, in <module>
    client.goToHome()
  File "/usr/local/lib/python2.7/dist-packages/plexapi/client.py", line 216, in goToHome
    self.sendCommand('navigation/home')
  File "/usr/local/lib/python2.7/dist-packages/plexapi/client.py", line 192, in sendCommand
    return self.query(key, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/plexapi/client.py", line 164, in query
    raise BadRequest('(%s) %s; %s %s' % (response.status_code, codename, response.url, errtext))
plexapi.exceptions.BadRequest: (406) not_acceptable; http://10.0.1.35:32433/player/navigation/home?commandID=1&X-Plex-Token=[MY TOKEN]
```

Is there any step i did forget to control my client ?
(i can navigate into my library thru the PlexServer object, list all my movies...)

```
#!/usr/bin/env python3

from plexapi.server import PlexServer

baseurl = 'http://10.0.1.41:32400'
token = '[MY TOKEN]'
plex = PlexServer(baseurl, token)

for client in plex.clients():
    print(client.title)

client = plex.client("PlexMediaPlayer")

client.connect()

client.goToHome()
```

**Comment by Hellowlol** [comment] 2018-01-03 11:02
Sometimes you get useful info. What happens if you pass the url in your browser, are there any error message from pmp?

**Comment by niko34** [comment] 2018-01-03 11:09
I only get a generic message in chrome : "Failed to load resource: the server responded with a status of 406 (Not Acceptable)".

**Comment by Hellowlol** [comment] 2018-01-03 13:00
Thanks, ill check.

**Comment by pkkid** [comment] 2018-01-03 14:32
The `/navigation` commands are hit more miss on many of the clients. I imagine even more so since the clients have been getting so many updates from the Plex team. You might want to try playing a media item directly to see if you get the same error.

**Comment by pkkid** [comment] 2018-01-03 14:35
@Hellowlol Would it make sense for us to also log the response body when we a bad request (400 level)? As you mentioned that's often where the useful error messages are sitting.

**Comment by pkkid** [comment] 2018-01-05 02:59
FWIW 406 = Not Acceptable

**Comment by Hellowlol** [comment] 2018-01-15 22:42
Yes. I think so.

**Comment by ryanm101** [comment] 2018-03-18 22:38
One of our users has reported the same issue. You might want to check out our ticket incase it provides any more detail

**Comment by Hellowlol** [comment] 2018-03-25 12:18
I know notice that I posted in the home assistant issue. Anyway pmp seems to require a timeline call every 90 sec or it throws a 406 on the command. 

You can fix this by using client.timeline()

**Comment by ryanm101** [comment] 2018-03-26 13:26
Just to answer your semi-rhetorical question in the HomeAssistant I would think it best handled in the at the API level if it can be done async. If not and it's going to block then it should be handled by the implementor.

**Comment by Hellowlol** [comment] 2018-03-26 13:53
Nothing about this api is asynchronous. Anyway I think we should handle this this is the client class.

**Comment by Hellowlol** [comment] 2018-03-26 14:20
If anybody want to send a pr please do if not I’ll fix this after I’m done with bw_plex

**Comment by Hellowlol** [comment] 2018-09-03 10:59
@doodah33 Today :)

**Comment by realfire23** [comment] 2018-09-20 05:59
any news out there ? iam getting the same error.

Also Iam unable to cast videos.

Problem appears when trying to cast on windows plex media player (which is indeed crucial for me, 
because of the orientation of screen.

**Comment by Hellowlol** [comment] 2018-11-17 00:48
I have tried to add a fix in https://github.com/pkkid/python-plexapi/tree/pmp_406 Can anybody test and confirm?

**Comment by beville** [comment] 2018-11-17 02:58
I just gave it go by copying client.py into my Home Assistant deps. The 406 error is gone, and I'm able to control the Plex Media Player on RPi.  

Nice work!

**Comment by Hellowlol** [comment] 2018-11-17 11:34
@beville you mind trying different actions like pause, stop, play, vol up down etc?

**Comment by beville** [comment] 2018-11-17 17:12
Yes, I tested play, pause, stop, volume up and down via the HA control, and all worked.

In addition, I used the test script from above at https://github.com/pkkid/python-plexapi/issues/244#issue-285652346, and the goToHome function seemed to work.

Since this problem seems to affect PMP regardless of platform, you should be able to easily verify yourself against any desktop version of PMP.  I just started a Linux version of PMP (https://knapsu.eu/plex/), and was able to pause/play with a script using your fixed version of client.py.

**Comment by Hellowlol** [comment] 2019-01-19 23:43
Closing this as the pr is merged in master.

**Closed by Hellowlol** 2019-01-19 23:43 UTC
Labels: bug

**Comment by jjlawren** [comment] 2020-09-15 21:25
While researching some details around `timeline()` I figured I'd test if this workaround is still necessary. Unfortunately I can still reproduce the problem in the latest version (v2.58.0) which was released in May 2020. Too bad.
