### ISSUE TITLE
cancel pending invite

### ISSUE THREAD

**Issue by joshdev-de** [pkkid/python-plexapi#558] opened 2020-08-25 01:21 UTC
I cannot find a way to cancel a pending invite.
When trying to `removeFriend("xxxxx")` or `updateFriend("xxxxx")` the friend is not found.
In `plexapi.myplex.MyPlexAccount.users()` I can see the invite, but cannot cancel it from there.
Is there a way?

**Comment by blacktwin** [comment] 2020-08-25 13:34
Confirmed. 

`REMOVEINVITE = 'https://plex.tv/api/invites/requested/{userId}?friend=1&server=0&home=0'  `

friend, server, and home params are hardcoded and likely the root cause of the issue. Thanks for identifying this issue. We'll need to figure out what those params are linked to. I assume if friend and not in the home then friend=1&home=0, if friend and in the home then friend=1&home=1. Does server param mean they exist or have access to the server? Will this always be server=1?

**Comment by blacktwin** [comment] 2020-08-26 04:04
`friend=1&server=1&home=1' seems to work when inviting a new user to the server as a normal remote user and if added as a Home User.

**Comment by Sleepingpirates** [comment] 2020-09-08 04:25
> I cannot find a way to cancel a pending invite.
> 
> When trying to `removeFriend("xxxxx")` or `updateFriend("xxxxx")` the friend is not found.
> 
> In `plexapi.myplex.MyPlexAccount.users()` I can see the invite, but cannot cancel it from there.
> 
> Is there a way?
> 
> 

I need help with this too. I have the same issue. Is there anyway to cancel the invite?

**Comment by blacktwin** [comment] 2021-01-19 18:01
@Sleepingpirates @joshdev-de This issue has been addressed and merged into master.

**Closed by blacktwin** 2021-01-19 18:01 UTC
