### ISSUE TITLE
Error searching to Duplicates

### ISSUE THREAD

**Issue by speedyflipper** [pkkid/python-plexapi#696] opened 2021-03-16 22:00 UTC
When I run the below code with version 4.2.0, I get "plexapi.exceptions.BadRequest: Unknown filter category: duplicate". However it works perfectly in 3.2.0

```
from plexapi.server import PlexServer
plex_host="http://localhost:32400"
plex_api="XXXXXXXXXXXXXXXXX"
plex = PlexServer(plex_host, plex_api)
plex.library.sections()[0].search(duplicate=True)
```

**Comment by JonnyWong16** [comment] 2021-03-17 00:45
Duplicate of #623 and #691.

**Closed** 2021-03-17 00:46 UTC
Labels: duplicate
