### ISSUE TITLE
[Bug] part.streams and part.AudioStreams() return empty lists.

### ISSUE THREAD

**Issue by JakeStanger** [pkkid/python-plexapi#310] opened 2018-10-23 19:32 UTC
Getting a track, getting the track part, and then getting the streams for that track part returns and empty list. This is happening for all tracks.

This code:
```python
 track_part: MediaPart = [*track.iterParts()][0]
print(track_part.audioStreams())
print(track_part.streams)
print(track_part.duration)
```
Returns:
```
[]
[]
445649
```
So the part is definitely being fetched correctly.

Using `requests.get` I have confirmed the stream data does exist, as I am getting back valid JSON.

I can use a second request using `get` for now but obviously doubling the number of requests isn't great by any means. I'm also happy to help with this if I'm given some pointers.

**Comment by Hellowlol** [comment] 2018-10-23 20:13
We are parsing xml not json. Check the url manually and see if it exists in the xml.

**Comment by JakeStanger** [comment] 2018-10-23 20:17
I understand this. My JSON request was an entirely separate request direct to my server to check the integrity of the data. I requested JSON for ease however I can also verify it exists in the XML.

**Comment by Hellowlol** [comment] 2018-10-23 20:20
Also reload() the object. Depending now how you «found» the item you might reload to get all details

**Comment by pkkid** [comment] 2018-10-24 13:03
I believe Hellowlol is correct, that you are probably missing a `reload()`. The issue is that when you search or list all objects in a library, the response from Plex is often incomplete for each item to help keep the amount of data being returned down. In plexapi we will still serve that object to you, but you may need to reload() that object which tells the api to go fetch all the information available. Someting like this should get you up and running.

```python
track = <whatever_you_did_to_get_a_track>
track.reload()
track_part: MediaPart = [*track.iterParts()][0]
print(track_part.audioStreams())
print(track_part.streams)
print(track_part.duration)
```

**Comment by pkkid** [comment] 2018-11-06 14:09
Closing as I believe we answered this question. If you are still stuck, feel free to reopen.

**Closed by pkkid** 2018-11-06 14:09 UTC
Labels: question

**Comment by JakeStanger** [comment] 2018-11-06 21:33
Apologies, I forgot to reply. Yes this solved the problem, thank you.
